# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.IntegerField()),
                ('lightshow', models.IntegerField()),
                ('outfit', models.IntegerField()),
                ('melody', models.IntegerField()),
                ('voice', models.IntegerField()),
                ('esc_factor', models.IntegerField()),
                ('sexyness', models.IntegerField()),
                ('douchebag', models.IntegerField()),
                ('modulation', models.IntegerField()),
                ('dress_change', models.IntegerField()),
                ('language', models.IntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
