# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170409_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='artbreak',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
