# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_vote_artbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
