# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_party_userparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
