# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:28
from __future__ import unicode_literals

from django.db import migrations

def add_first_contest(apps, schema_editor):
    Contest = apps.get_model('website', 'Contest')
    first_contest = Contest()
    first_contest.year = 2017
    first_contest.country = 'Ukraine'
    first_contest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contest'),
    ]

    operations = [
        migrations.RunPython(add_first_contest)
    ]
