# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180510_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Contest'),
            preserve_default=False,
        ),
    ]
