# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180510_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparty',
            name='easy_mode',
            field=models.BooleanField(default=True),
        ),
    ]
